tasks:
  - name: Install Dependencies & Start Dev Server
    init: |
      npm install
      npm run build
    command: |
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
